config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
   resources :relationships, only: [:create, :destroy]
  root  'pages#home'
  match '/signup',  to: 'users#new',            via: :get
  match '/signin',  to: 'sessions#new',         via: :get
  match '/signout', to: 'sessions#destroy',     via: :delete
  
  match '/signup', to: 'users#new', via: :get

  resources :users
  match '/about', to: 'pages#about', via: :get
  match '/contacts', to: 'pages#contacts', via: :get
  match '/help', to: 'pages#help', via: :get
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://web.method.kz/">Курс веб-программирования</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "О нас",   about_path %></li>
      <li><%= link_to "Контакты", contacts_path %></li>
      <li><a href="http://news.railstutorial.org/">Новости</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Twitter", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Главная", root_path %></li>
        <li><%= link_to "Помощь", help_path %></li>
        <% if signed_in? %>
          <li><%= link_to "Пользователи", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Профиль", current_user %></li>
              <li><%= link_to "Настройки", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Выход", signout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Войти", signin_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
   <%= render 'layouts/shim'%>
  </head>
  <body>
   <%= render 'layouts/header'%>
  
    <div class="container">
        <%= render 'shared/flash_messages'%>
          <%= yield %>
      <%= render 'layouts/footer'%>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>